FROM registry.access.redhat.com/ubi9/openjdk-25-runtime

WORKDIR /work/

COPY target/quarkus-app/lib/ /work/lib/
COPY target/quarkus-app/*.jar /work/
COPY target/quarkus-app/app/ /work/app/
COPY target/quarkus-app/quarkus/ /work/quarkus/

EXPOSE 8080

USER 185

ENTRYPOINT ["java", "-jar", "/work/quarkus-run.jar"]
